/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Citepoint Champagne Gold & Alabaster Luxury Tokens
        primary: {
          DEFAULT: '#C5A059',
          hover: '#DFB76C',
          focus: '#B88E3A',
          on: '#0F1012',
        },
        ink: {
          DEFAULT: '#0F1012',
          muted: '#363940',
          subtle: '#4B4F58',
          tertiary: '#6E7380',
        },
        canvas: {
          DEFAULT: '#FAF8F5',
          inverse: '#0F1012',
        },
        surface: {
          1: '#ffffff',
          2: '#F7F4EE',
          3: '#F0EAE0',
          4: '#E8E0D2',
        },
        hairline: {
          DEFAULT: '#EADBBE',
          strong: '#D5C39E',
          tertiary: '#C4AE7E',
        },
        'brand-secure': '#9E7427',
        'semantic-success': '#1E8E3E',
        'semantic-overlay': 'rgba(15, 16, 18, 0.4)',

        // Backward compatibility mappings to Champagne Gold & Alabaster
        'liquid-abyss': '#FAF8F5',
        'liquid-deep': '#F7F4EE',
        'liquid-kelp': '#ffffff',
        'liquid-mist': '#0F1012',
        'platinum': '#0F1012',
        'silver-mist': '#4B4F58',
        'ash': '#363940',
        'slate-deep': '#EADBBE',
        'lavender-phosphor': '#C5A059',
        'bioluminescent': '#C5A059',
        'aurora-cyan': '#DFB76C',

        brand: {
          abyss: '#FAF8F5',
          deep: '#F7F4EE',
          kelp: '#ffffff',
          mist: '#0F1012',
          platinum: '#0F1012',
          silver: '#4B4F58',
          slate: '#EADBBE',
          pink: '#DFB76C',
          'deep-navy': '#FAF8F5',
          'midnight': '#F7F4EE',
          'dark-slate': '#ffffff',
          navy: '#FAF8F5',
          charcoal: '#F7F4EE',
          gold: '#C5A059',
          'warm-gold': '#C5A059',
          'light-gold': '#DFB76C',
          champagne: '#FAF8F5',
          'gold-wash': 'rgba(197, 160, 89, 0.08)',
          cream: '#FAF8F5',
          'soft-cream': '#F7F4EE',
          white: '#ffffff',
          'pure-white': '#ffffff',
          'blue-gray': '#F0EAE0',
          ink: '#0F1012',
          muted: '#4B4F58',
          'border-gray': '#EADBBE',
          blue: '#C5A059',
          'glass-border': '#EADBBE',
          'glass-bright': '#D5C39E',
          'glass-shadow': '0 8px 30px rgba(197, 160, 89, 0.08)',
        }
      },
      backgroundImage: {
        'linear-gradient': 'linear-gradient(180deg, rgba(197, 160, 89, 0.12) 0%, rgba(250, 248, 245, 0) 100%)',
        'surface-highlight': 'linear-gradient(90deg, transparent 0%, rgba(197, 160, 89, 0.25) 50%, transparent 100%)',
        'aurora-gradient': 'linear-gradient(135deg, #DFB76C 0%, #C5A059 50%, #B88E3A 100%)',
        'bioluminescent-gradient': 'linear-gradient(135deg, #DFB76C 0%, #C5A059 50%, #B88E3A 100%)',
      },
      borderRadius: {
        none: '0',
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '24px',
        pill: '9999px',
        full: '9999px',
        // Component defaults from Linear spec
        buttons: '8px',
        cards: '12px',
        small: '6px',
        DEFAULT: '8px',
      },
      fontFamily: {
        sans: ['"Inter Tight"', '"Inter"', 'SF Pro Display', '-apple-system', 'system-ui', 'sans-serif'],
        matter: ['"Inter Tight"', '"Inter"', 'SF Pro Display', '-apple-system', 'system-ui', 'sans-serif'],
        heading: ['"Bricolage Grotesque"', '"Inter Tight"', '"Inter"', 'system-ui', 'sans-serif'],
        display: ['"Bricolage Grotesque"', '"Inter Tight"', '"Inter"', 'system-ui', 'sans-serif'],
        arial: ['"Inter Tight"', '"Inter"', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', '"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      letterSpacing: {
        eyebrow: '0.4px',
        kicker: '0.4px',
        tightest: '-0.04em',
        tighter: '-0.03em',
        tight: '-0.02em',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'section': '96px',
        '12': '12px',
        '16': '16px',
        '20': '20px',
        '24': '24px',
        '28': '28px',
        '32': '32px',
        '36': '36px',
        '40': '40px',
        '48': '48px',
        '64': '64px',
        '68': '68px',
        '80': '80px',
        '88': '88px',
        '96': '96px',
        '104': '104px',
        '112': '112px',
        '120': '120px',
        '128': '128px',
        '140': '140px',
        '144': '144px',
        '152': '152px',
        '160': '160px',
        '164': '164px',
        '180': '180px',
        '192': '192px',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-4px)' },
        },
      }
    },
  },
  plugins: [],
}
